files:
  include: 
    - "./**/**/*.s+(a|c)ss"
    - "./**/*.s+(a|c)ss"
options:
  formatter: stylish
  merge-default-rules: true
rules:
  nesting-depth:
    - 1
    - max-depth: 3
  class-name-format:
    - 1
    - convention: hyphenatedbem
